version: "3"
services:
  nuxt: # Nuxt.js(フロントエンド)の設定
    build: #Docker Imageをbuildするための設定
      context: nuxt/ #Dockerfileの場所
      args: # Docker Imageをbuildする際一時的に環境変数に使われたりするグローバル変数
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
        - FTP_PROXY=$FTP_PROXY
        - ftp_proxy=$ftp_proxy
    ports: # ホスト:コンテナでPortを対応付ける
      - "8001:3000"
    volumes: # ホストのディレクトリ:コンテナのディレクトリで指定し同期する
      - "./nuxt/app:/app"
    environment: # コンテナ内に渡される環境変数
      - HOST=$HOST
      - TZ=$TZ
      - HTTP_PROXY=$HTTP_PROXY
      - http_proxy=$http_proxy
      - HTTPS_PROXY=$HTTPS_PROXY
      - https_proxy=$https_proxy
      - FTP_PROXY=$FTP_PROXY
      - ftp_proxy=$ftp_proxy
    command: > # コンテナを立ち上げたタイミングで実行されるコマンド
      npm run dev
  flask:
    build:
      context: flask/
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
        - FTP_PROXY=$FTP_PROXY
        - ftp_proxy=$ftp_proxy
    ports:
      - "8002:5000"
    volumes:
      - "./flask/app:/app"
    environment:
      - HOST=$HOST
      - TZ=$TZ
      - HTTP_PROXY=$HTTP_PROXY
      - http_proxy=$http_proxy
      - HTTPS_PROXY=$HTTPS_PROXY
      - https_proxy=$https_proxy
      - FTP_PROXY=$FTP_PROXY
      - ftp_proxy=$ftp_proxy
    command: >
      flask run --host 0.0.0.0 --port 5000
  db:
    image: mariadb:10.5
    ports:
    - "3306:3306"
    volumes:
    - "./db/data:/var/lib/mysql"
    - "./db/initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD

    
