version: "3"
services:
  front: # Nuxt.js(フロントエンド)の設定
    build: #Docker Imageをbuildするための設定
      context: front/ #Dockerfileの場所
    ports: # ホスト:コンテナでPortを対応付ける
      - "8001:3000"
    volumes: # ホストのディレクトリ:コンテナのディレクトリで指定し同期する
      - "./front/app:/app"
    tty: true
    environment: # コンテナ内に渡される環境変数
      - HOST
      - TZ

  api:
    build:
      context: api/
    ports:
      - "8002:5000"
    volumes:
      - "./api/app:/app"
    environment:
      - HOST
      - TZ
    command: >
      flask run --host 0.0.0.0 --port 5000
  db:
    image: mariadb:10.5
    ports:
    - "3306:3306"
    volumes:
    - "./db/data:/var/lib/mysql"
    - "./db/initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - HOST
      - TZ
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

    
